include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - annotate_overrides
    - avoid_print
    - avoid_redundant_argument_values
    - avoid_unnecessary_containers
    - cancel_subscriptions
    - close_sinks
    - directives_ordering
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_locals
    - prefer_single_quotes
    - unnecessary_lambdas
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - use_key_in_widget_constructors
    - use_super_parameters
